# Generated by Django 5.1.6 on 2025-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
