# Generated by Django 5.1.6 on 2025-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromodel',
            name='documento',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
